import type { Env } from '../types';
import { summarizeAndTag } from './haiku';
import { summarizeAndTagGemma } from './gemma';
import { embedAndUpsert } from './vector';
import type { SummarizeInput, SummaryResult } from './prompts';
import { detectYouTube, fetchTranscript, fetchYouTubeMetadata } from './youtube';

const USER_AGENT = 'Mozilla/5.0 (compatible; AIBookmarks/0.1)';
const FETCH_TIMEOUT_MS = 8000;
const MAX_EXCERPT_CHARS = 3000;

export async function enrich(env: Env, bookmarkId: number): Promise<void> {
  const row = await env.DB
    .prepare('SELECT id, url FROM bookmarks WHERE id = ?')
    .bind(bookmarkId)
    .first<{ id: number; url: string }>();
  if (!row) return;

  try {
    const extract = await extractForEnrichment(row.url);

    let summary: string | null = null;
    let tags: string[] = [];
    if (extract.summarizeInput) {
      const ai = await summarizeWithFallback(env, extract.summarizeInput);
      if (ai) {
        summary = ai.summary || null;
        tags = ai.tags;
      }
    }

    await env.DB.prepare(`
      UPDATE bookmarks
      SET title           = COALESCE(?, title),
          og_image_url    = ?,
          og_description  = ?,
          content_excerpt = ?,
          ai_summary      = ?,
          ai_tags         = ?,
          content_type    = ?,
          metadata        = ?,
          status          = ?,
          updated_at      = ?
      WHERE id = ?
    `).bind(
      extract.title,
      extract.ogImage,
      extract.ogDescription,
      extract.excerpt,
      summary,
      JSON.stringify(tags),
      extract.contentType,
      JSON.stringify(extract.metadata),
      summary ? 'active' : 'partial',
      Date.now(),
      bookmarkId,
    ).run();

    // Best-effort vector upsert. Failure here doesn't fail enrichment —
    // the bookmark stays searchable by title/tags even without semantic.
    if (summary) {
      try {
        await embedAndUpsert(env, bookmarkId, {
          title: extract.title,
          summary,
          excerpt: extract.excerpt,
          videoContext: extract.videoContext,
        });
      } catch (err) {
        console.error('vector upsert failed', err);
      }
    }
  } catch (err) {
    console.error('enrich failed', err);
    await env.DB
      .prepare(`UPDATE bookmarks SET status = 'partial', updated_at = ? WHERE id = ?`)
      .bind(Date.now(), bookmarkId)
      .run();
  }
}

interface EnrichmentExtract {
  title: string | null;
  ogImage: string | null;
  ogDescription: string | null;
  excerpt: string | null;
  contentType: 'video' | null;
  metadata: Record<string, unknown>;
  summarizeInput: SummarizeInput | null;
  videoContext?: { channel: string | null; durationSec: number | null };
}

async function extractForEnrichment(url: string): Promise<EnrichmentExtract> {
  const yt = detectYouTube(url);
  if (yt) return extractYouTube(yt.videoId);
  return extractArticle(url);
}

// YouTube branch: oEmbed + ld+json metadata in parallel with transcript. The
// transcript becomes the excerpt when available (richer for semantic search
// than the ~250-char description); otherwise we fall back to description.
// Any YouTube fetch failing doesn't throw — we return whatever metadata we
// got so the bookmark still lands with content_type='video' + a thumbnail.
async function extractYouTube(videoId: string): Promise<EnrichmentExtract> {
  const [meta, transcript] = await Promise.all([
    fetchYouTubeMetadata(videoId),
    fetchTranscript(videoId),
  ]);

  const excerpt = transcript?.text ?? meta.description ?? null;
  const metadata: Record<string, unknown> = {
    videoId,
    ...(meta.channel ? { channel: meta.channel } : {}),
    ...(meta.durationSec ? { durationSec: meta.durationSec } : {}),
    ...(meta.publishedAt ? { publishedAt: meta.publishedAt } : {}),
    ...(transcript ? { captionsAvailable: true, captionsAuto: transcript.isAutoGenerated } : { captionsAvailable: false }),
  };

  const summarizeInput: SummarizeInput | null = excerpt
    ? {
        kind: 'video',
        title: meta.title ?? undefined,
        excerpt,
        channel: meta.channel ?? undefined,
        durationSec: meta.durationSec ?? undefined,
      }
    : null;

  return {
    title: meta.title,
    ogImage: meta.thumbnailUrl,
    ogDescription: meta.description,
    excerpt,
    contentType: 'video',
    metadata,
    summarizeInput,
    videoContext: { channel: meta.channel, durationSec: meta.durationSec },
  };
}

// Article branch: unchanged pipeline — fetch HTML, HTMLRewriter title +
// og:image + og:description + <p> excerpt. content_type stays null so the
// UI treats it as a generic bookmark.
async function extractArticle(url: string): Promise<EnrichmentExtract> {
  const page = await extractPage(url);
  return {
    title: page.title,
    ogImage: page.ogImage,
    ogDescription: page.ogDescription,
    excerpt: page.excerpt,
    contentType: null,
    metadata: {},
    summarizeInput: page.excerpt
      ? { title: page.title ?? undefined, excerpt: page.excerpt }
      : null,
  };
}

interface ExtractedPage {
  title: string | null;
  ogImage: string | null;
  ogDescription: string | null;
  excerpt: string | null;
}

async function extractPage(url: string): Promise<ExtractedPage> {
  const resp = await fetch(url, {
    headers: { 'User-Agent': USER_AGENT, Accept: 'text/html,*/*' },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    redirect: 'follow',
  });
  if (!resp.ok) throw new Error(`fetch ${resp.status}`);

  const contentType = resp.headers.get('content-type') ?? '';
  if (!contentType.includes('text/html')) {
    throw new Error(`non-html content-type: ${contentType}`);
  }

  let title = '';
  let ogImage = '';
  let ogDescription = '';
  const excerptParts: string[] = [];
  let excerptLen = 0;

  const rewriter = new HTMLRewriter()
    .on('title', {
      text(t) { title += t.text; },
    })
    .on('meta[property="og:image"]', {
      element(el) { ogImage = el.getAttribute('content') ?? ''; },
    })
    .on('meta[property="og:description"]', {
      element(el) { ogDescription = el.getAttribute('content') ?? ''; },
    })
    .on('p', {
      text(t) {
        if (excerptLen >= MAX_EXCERPT_CHARS) return;
        const remaining = MAX_EXCERPT_CHARS - excerptLen;
        const piece = t.text.length > remaining ? t.text.slice(0, remaining) : t.text;
        excerptParts.push(piece);
        excerptLen += piece.length;
      },
    });

  await rewriter.transform(resp).text();

  const excerpt = excerptParts.join(' ').replace(/\s+/g, ' ').trim();
  return {
    title: title.trim() || null,
    ogImage: ogImage || null,
    ogDescription: ogDescription || null,
    excerpt: excerpt || null,
  };
}

// Gemma is ~10× cheaper than Haiku and handles the vast majority of pages
// fine. When it can't parse or the AI binding errors, fall back to Haiku so
// the bookmark still gets enriched. Log each branch so fallback rate is
// observable in `wrangler tail`.
async function summarizeWithFallback(
  env: Env,
  input: SummarizeInput,
): Promise<SummaryResult | null> {
  try {
    const gemma = await summarizeAndTagGemma(env, input);
    if (gemma) {
      console.log('enrich:gemma-hit');
      return gemma;
    }
  } catch (err) {
    console.error('gemma failed', err);
  }

  if (!env.ANTHROPIC_API_KEY) {
    console.error('enrich:both-failed (no ANTHROPIC_API_KEY for Haiku fallback)');
    return null;
  }

  try {
    const haiku = await summarizeAndTag(env, input);
    console.log('enrich:haiku-fallback');
    return haiku;
  } catch (err) {
    console.error('enrich:both-failed', err);
    return null;
  }
}
