// YouTube-specific enrichment helpers.
//
// Three entry points:
//   detectYouTube        — pure URL → videoId (no network)
//   fetchYouTubeMetadata — oEmbed + ld+json VideoObject scrape
//   fetchTranscript      — timedtext captions (best-effort, may return null)
//
// All network callers share the same UA + 8-second timeout as extractPage().
// Failures degrade: missing transcript → description-only excerpt; missing
// oEmbed → fall back to ld+json; missing ld+json → whatever oEmbed gave.

const USER_AGENT = 'Mozilla/5.0 (compatible; AIBookmarks/0.1)';
const FETCH_TIMEOUT_MS = 8000;
const MAX_TRANSCRIPT_CHARS = 3000;

export interface YouTubeHit {
  videoId: string;
}

export interface YouTubeMetadata {
  videoId: string;
  title: string | null;
  channel: string | null;
  description: string | null;
  thumbnailUrl: string | null;
  durationSec: number | null;
  publishedAt: string | null; // ISO date string from uploadDate
}

export interface TranscriptResult {
  text: string;
  isAutoGenerated: boolean;
  languageCode: string;
}

// Covers the shapes YouTube actually hands out in the wild:
//   https://www.youtube.com/watch?v=ID[&…]
//   https://youtu.be/ID
//   https://www.youtube.com/shorts/ID
//   https://www.youtube.com/live/ID
//   https://m.youtube.com/watch?v=ID
//   https://music.youtube.com/watch?v=ID   ← treat as video for MVP
// Ignores /playlist, /channel, /@handle, /results — those aren't single videos.
export function detectYouTube(url: string): YouTubeHit | null {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }

  const host = parsed.hostname.toLowerCase();
  if (host === 'youtu.be') {
    const id = parsed.pathname.slice(1).split('/')[0];
    return isVideoId(id) ? { videoId: id } : null;
  }

  if (!/(^|\.)youtube\.com$/.test(host)) return null;

  const path = parsed.pathname;
  if (path === '/watch') {
    const id = parsed.searchParams.get('v');
    return id && isVideoId(id) ? { videoId: id } : null;
  }

  const shortMatch = path.match(/^\/(?:shorts|live|embed)\/([^/?#]+)/);
  if (shortMatch) {
    const id = shortMatch[1];
    return isVideoId(id) ? { videoId: id } : null;
  }

  return null;
}

// YouTube video IDs are 11 chars of [A-Za-z0-9_-]. Validating here keeps us
// from firing a network request for a path fragment that just happens to
// look vaguely like /watch.
function isVideoId(id: string | undefined | null): id is string {
  return !!id && /^[A-Za-z0-9_-]{11}$/.test(id);
}

export async function fetchYouTubeMetadata(videoId: string): Promise<YouTubeMetadata> {
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;

  const [oembed, page] = await Promise.all([
    fetchOEmbed(watchUrl).catch((err) => {
      console.warn('youtube:oembed-failed', err);
      return null;
    }),
    fetchWatchPage(watchUrl).catch((err) => {
      console.warn('youtube:page-failed', err);
      return null;
    }),
  ]);

  return {
    videoId,
    title: page?.title ?? oembed?.title ?? null,
    channel: oembed?.author_name ?? page?.channel ?? null,
    description: page?.description ?? null,
    thumbnailUrl: oembed?.thumbnail_url ?? page?.thumbnailUrl ?? `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    durationSec: page?.durationSec ?? null,
    publishedAt: page?.uploadDate ?? null,
  };
}

interface OEmbedResponse {
  title?: string;
  author_name?: string;
  thumbnail_url?: string;
}

async function fetchOEmbed(watchUrl: string): Promise<OEmbedResponse | null> {
  const url = `https://www.youtube.com/oembed?url=${encodeURIComponent(watchUrl)}&format=json`;
  const resp = await fetch(url, {
    headers: { 'User-Agent': USER_AGENT },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  if (!resp.ok) throw new Error(`oembed ${resp.status}`);
  return (await resp.json()) as OEmbedResponse;
}

interface WatchPageData {
  title: string | null;
  description: string | null;
  channel: string | null;
  thumbnailUrl: string | null;
  durationSec: number | null;
  uploadDate: string | null;
}

// Scrapes the watch page for the VideoObject ld+json block. YouTube also
// emits BreadcrumbList and sometimes ItemList in the same page, so we
// accumulate every ld+json script and pick the first one that looks like
// a VideoObject.
async function fetchWatchPage(watchUrl: string): Promise<WatchPageData> {
  const resp = await fetch(watchUrl, {
    headers: { 'User-Agent': USER_AGENT, Accept: 'text/html,*/*' },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    redirect: 'follow',
  });
  if (!resp.ok) throw new Error(`watch ${resp.status}`);

  let title = '';
  const ldBlocks: string[] = [];
  let currentLd = '';
  let capturingLd = false;

  const rewriter = new HTMLRewriter()
    .on('title', {
      text(t) { title += t.text; },
    })
    .on('script[type="application/ld+json"]', {
      element() { currentLd = ''; capturingLd = true; },
      text(t) {
        if (capturingLd) currentLd += t.text;
        if (capturingLd && t.lastInTextNode) {
          ldBlocks.push(currentLd);
          currentLd = '';
          capturingLd = false;
        }
      },
    });

  await rewriter.transform(resp).text();

  const video = pickVideoObject(ldBlocks);

  return {
    title: title.trim() || video?.name || null,
    description: typeof video?.description === 'string' ? video.description : null,
    channel: extractChannel(video),
    thumbnailUrl: extractThumbnail(video),
    durationSec: parseIso8601Duration(typeof video?.duration === 'string' ? video.duration : null),
    uploadDate: typeof video?.uploadDate === 'string' ? video.uploadDate : null,
  };
}

interface VideoObject {
  '@type'?: string | string[];
  name?: string;
  description?: string;
  duration?: string;
  uploadDate?: string;
  thumbnailUrl?: string | string[];
  author?: { name?: string } | string;
  channel?: { name?: string };
}

function pickVideoObject(blocks: string[]): VideoObject | null {
  for (const raw of blocks) {
    try {
      const parsed = JSON.parse(raw);
      const found = findVideoObject(parsed);
      if (found) return found;
    } catch {
      // ignore unparseable blocks — YouTube occasionally wraps HTML comments
    }
  }
  return null;
}

function findVideoObject(node: unknown): VideoObject | null {
  if (!node || typeof node !== 'object') return null;
  if (Array.isArray(node)) {
    for (const item of node) {
      const found = findVideoObject(item);
      if (found) return found;
    }
    return null;
  }
  const obj = node as VideoObject & { '@graph'?: unknown };
  const type = obj['@type'];
  if (type === 'VideoObject' || (Array.isArray(type) && type.includes('VideoObject'))) {
    return obj;
  }
  if (obj['@graph']) return findVideoObject(obj['@graph']);
  return null;
}

function extractChannel(video: VideoObject | null): string | null {
  if (!video) return null;
  if (typeof video.author === 'string') return video.author;
  if (video.author && typeof video.author.name === 'string') return video.author.name;
  if (video.channel && typeof video.channel.name === 'string') return video.channel.name;
  return null;
}

function extractThumbnail(video: VideoObject | null): string | null {
  if (!video?.thumbnailUrl) return null;
  if (Array.isArray(video.thumbnailUrl)) return video.thumbnailUrl[0] ?? null;
  return video.thumbnailUrl;
}

// ISO 8601 duration: PT#H#M#S (any component may be missing).
// Only supports hours/minutes/seconds — videos don't have P#D/P#Y durations.
export function parseIso8601Duration(iso: string | null): number | null {
  if (!iso) return null;
  const m = iso.match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?$/);
  if (!m) return null;
  const h = Number(m[1] ?? 0);
  const mm = Number(m[2] ?? 0);
  const s = Number(m[3] ?? 0);
  const total = h * 3600 + mm * 60 + s;
  return Number.isFinite(total) && total > 0 ? Math.round(total) : null;
}

// timedtext is an undocumented endpoint. It periodically tightens (adds
// login walls, rate limits, or shifts XML shape) — treat every success as
// a gift and every failure as expected. Returns null on any hiccup.
export async function fetchTranscript(videoId: string): Promise<TranscriptResult | null> {
  try {
    const tracks = await listTranscriptTracks(videoId);
    if (!tracks.length) {
      console.log('youtube:no-tracks', videoId);
      return null;
    }

    // Prefer manual English captions; fall back to auto-generated (asr) if
    // that's all the uploader enabled. Non-English is rejected — the embedder
    // is bge-base-en-v1.5, mixing a French transcript would hurt search more
    // than the missing text does.
    const english = tracks.filter((t) => t.langCode.startsWith('en'));
    const chosen = english.find((t) => !t.isAsr) ?? english[0];
    if (!chosen) {
      console.log('youtube:no-english', videoId);
      return null;
    }

    const text = await fetchTranscriptText(videoId, chosen);
    if (!text) return null;

    const capped = text.length > MAX_TRANSCRIPT_CHARS
      ? text.slice(0, MAX_TRANSCRIPT_CHARS)
      : text;

    return { text: capped, isAutoGenerated: chosen.isAsr, languageCode: chosen.langCode };
  } catch (err) {
    console.warn('youtube:transcript-failed', videoId, err);
    return null;
  }
}

interface TrackInfo {
  langCode: string;
  name: string;
  isAsr: boolean;
}

async function listTranscriptTracks(videoId: string): Promise<TrackInfo[]> {
  const url = `https://video.google.com/timedtext?type=list&v=${videoId}`;
  const resp = await fetch(url, {
    headers: { 'User-Agent': USER_AGENT },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  if (!resp.ok) return [];
  const xml = await resp.text();
  if (!xml.includes('<track')) return [];

  const tracks: TrackInfo[] = [];
  for (const match of xml.matchAll(/<track\b([^>]*)\/>/g)) {
    const attrs = match[1] ?? '';
    const lang = /\blang_code="([^"]*)"/.exec(attrs)?.[1] ?? '';
    const name = /\bname="([^"]*)"/.exec(attrs)?.[1] ?? '';
    const kind = /\bkind="([^"]*)"/.exec(attrs)?.[1] ?? '';
    if (lang) tracks.push({ langCode: lang, name, isAsr: kind === 'asr' });
  }
  return tracks;
}

async function fetchTranscriptText(videoId: string, track: TrackInfo): Promise<string | null> {
  const params = new URLSearchParams({ lang: track.langCode, v: videoId });
  if (track.name) params.set('name', track.name);
  if (track.isAsr) params.set('kind', 'asr');
  const url = `https://video.google.com/timedtext?${params.toString()}`;

  const resp = await fetch(url, {
    headers: { 'User-Agent': USER_AGENT },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  if (!resp.ok) return null;
  const xml = await resp.text();
  if (!xml) return null;

  const parts: string[] = [];
  for (const match of xml.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/g)) {
    parts.push(decodeTranscriptChunk(match[1] ?? ''));
    // Break early once we have more than we'll keep, plus a little slack
    // for whitespace collapse.
    if (parts.join(' ').length > MAX_TRANSCRIPT_CHARS + 500) break;
  }

  const joined = parts.join(' ').replace(/\s+/g, ' ').trim();
  return joined || null;
}

// YouTube double-encodes: the XML carries &amp;#39; for apostrophes, etc.
// Decode the outer XML entities first, then the inner HTML-ish entities.
function decodeTranscriptChunk(raw: string): string {
  const once = raw
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
  return once
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)));
}
